CREATE OR REPLACE VIEW ALPHABETICAL_LIST_OF_PRODUCTS
AS
    SELECT P.*,
           C.CATEGORY_NAME
      FROM CATEGORIES C
      JOIN PRODUCTS P ON C.CATEGORY_ID = P.CATEGORY_ID
     WHERE P.DISCONTINUED = 0; 
