CREATE OR REPLACE VIEW CUSTOMER_ORDERS_ORDERS
AS
      SELECT O.ORDER_ID,
             O.ORDER_DATE,
             O.REQUIRED_DATE,
             O.SHIPPED_DATE
        FROM ORDERS O
    ORDER BY O.ORDER_ID;