CREATE OR REPLACE VIEW CUSTOMER_ORDER_HISTORY
AS
        SELECT P.PRODUCT_NAME,
               SUM(OD.QUANTITY) AS TOTAL
          FROM PRODUCTS P
          JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID 
          JOIN ORDERS O ON OD.ORDER_ID = O.ORDER_ID 
          JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID 
      GROUP BY P.PRODUCT_NAME;