CREATE OR REPLACE VIEW CUSTOMER_AND_SUPPLIER_BY_CITY 
AS
    SELECT C.CITY,
           C.COMPANY_NAME,
           C.CONTACT_NAME,
           'CUSTOMERS' AS RELATIONSHIP
      FROM CUSTOMERS C
    UNION
    SELECT S.CITY,
           S.COMPANY_NAME,
           S.CONTACT_NAME,
           'SUPPLIERS' AS RELATIONSHIP
      FROM SUPPLIERS S;
