CREATE OR REPLACE VIEW CUSTOMER_ORDERS_DETAIL
AS
SELECT P.PRODUCT_NAME,
       ROUND(OD.UNIT_PRICE, 2) AS UNIT_PRICE,
       OD.QUANTITY,
        OD.DISCOUNT * 100 AS DISCOUNT, 
       ROUND(OD.QUANTITY * (1 - OD.DISCOUNT) * OD.UNIT_PRICE, 2) AS EXTENDED_PRICE
  FROM PRODUCTS P 
  JOIN ORDER_DETAILS OD ON  P.PRODUCT_ID = OD.PRODUCT_ID;