CREATE VIEW EMPLOYEE_SALES_BY_COUNTRY 
AS
    SELECT E.COUNTRY, 
           E.LAST_NAME, 
           E.FIRST_NAME, 
           O.SHIPPED_DATE, 
           O.ORDER_ID, 
           OST.SUB_TOTAL AS SALE_AMOUNT
      FROM ORDERS O 
      JOIN EMPLOYEES E ON O.EMPLOYEE_ID = E.EMPLOYEE_ID 
      JOIN ORDER_SUB_TOTALS OST ON O.ORDER_ID = OST.ORDER_ID;
    