CREATE VIEW ORDER_DETAILS_EXTENDED 
AS
    SELECT OD.ORDER_ID, 
           OD.PRODUCT_ID, 
           P.PRODUCT_NAME, 
           OD.UNIT_PRICE, 
           OD.QUANTITY, 
           OD.DISCOUNT, 
           OD.UNIT_PRICE * QUANTITY * (1 - DISCOUNT) AS EXTENDED_PRICE
    FROM PRODUCTS P 
    JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID;