CREATE VIEW PRODUCTS_BY_CATEGORY 
AS
    SELECT C.CATEGORY_NAME, 
           P.PRODUCT_NAME, 
           P.QUANTITY_PER_UNIT, 
           P.UNITS_IN_STOCK, 
           P.DISCONTINUED
      FROM CATEGORIES C
      JOIN PRODUCTS P ON C.CATEGORY_ID = P.CATEGORY_ID
     WHERE P.DISCONTINUED <> 1