CREATE OR REPLACE VIEW PRODUCT_SALES_FOR_1997 
AS
      SELECT C.CATEGORY_NAME, 
             P.PRODUCT_NAME, 
             SUM(OD.UNIT_PRICE * QUANTITY * (1 - DISCOUNT)) AS PRODUCT_SALES
        FROM ORDERS O 
        JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
        JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID 
        JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID 
       WHERE O.SHIPPED_DATE BETWEEN TO_DATE('19970101', 'YYYYMMDD') 
                                AND TO_DATE('19971231', 'YYYYMMDD')
    GROUP BY C.CATEGORY_NAME, 
             P.PRODUCT_NAME;