CREATE VIEW QUARTERLY_ORDERS 
AS
    SELECT DISTINCT 
           C.CUSTOMER_Id, 
           C.COMPANY_NAME, 
           C.CITY, 
           C.COUNTRY
      FROM CUSTOMERS C
RIGHT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
     WHERE O.ORDER_DATE BETWEEN TO_DATE('19970101', 'YYYYMMDD')
                            AND TO_DATE('19971231', 'YYYYMMDD');