CREATE VIEW SALES_TOTALS_BY_AMOUNT 
AS
    SELECT OS.SUB_TOTAL AS SALE_AMOUNT, 
           O.ORDER_ID, 
           C.COMPANY_NAME, 
           O.SHIPPED_DATE
      FROM ORDER_SUB_TOTALS OS 
      JOIN ORDERS O ON OS.ORDER_ID = O.ORDER_ID 
      JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID 
     WHERE OS.SUB_TOTAL > 2500 
       AND O.SHIPPED_DATE BETWEEN TO_DATE('19970101', 'YYYYMMDD')
                              AND TO_DATE('19971231', 'YYYYMMDD');