CREATE VIEW SALES_BY_YEAR 
AS
    SELECT O.SHIPPED_DATE, 
           O.ORDER_ID, 
           OST.SUb_TOTAL, 
           TO_CHAR(O.SHIPPED_DATE, 'YYYY') AS YEAR
    FROM ORDERS O
    JOIN ORDER_SUB_TOTALS OST ON O.ORDER_ID = OST.ORDER_ID;