CREATE OR REPLACE VIEW SALES_BY_CATEGORY_1998
AS
      SELECT P.PRODUCT_NAME,
             ROUND(SUM(OD.QUANTITY * (1-OD.DISCOUNT) * OD.UNIT_PRICE), 0) AS TotalPurchase,
             C.CATEGORY_NAME 
        FROM ORDER_DETAILS OD 
        JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID 
        JOIN ORDERS O ON OD.ORDER_ID = O.ORDER_ID 
        JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
       WHERE O.ORDER_DATE BETWEEN TO_DATE('19980101', 'YYYYMMDD')
                              AND TO_DATE('19981231', 'YYYYMMDD')
    GROUP BY P.PRODUCT_NAME,
             C.CATEGORY_NAME
    ORDER BY P.PRODUCT_NAME