CREATE VIEW SALES_BY_CATEGORY_1997 
AS
      SELECT C.CATEGORY_ID, 
             C.CATEGORY_NAME, 
             P.PRODUCT_NAME, 
             SUM(ODE.EXTENDED_PRICE) AS PRODUCT_SALES
        FROM ORDERS O
        JOIN ORDER_DETAILS_EXTENDED ODE ON O.ORDER_ID = ODE.ORDER_ID 
        JOIN PRODUCTS P ON ODE.PRODUCT_ID = P.PRODUCT_ID 
        JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID 
       WHERE O.ORDER_DATE BETWEEN TO_DATE('19970101', 'YYYYMMDD')
                              AND TO_DATE('19971231', 'YYYYMMDD')
    GROUP BY C.CATEGORY_ID, 
             C.CATEGORY_NAME, 
             P.PRODUCT_NAME;