DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'DISCOUNTS';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE DISCOUNTS CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE DISCOUNTS(
    DISCOUNT_TYPE VARCHAR2(40) NOT NULL,
    STORE_ID CHAR(4),
    LOWER_QUANTITY NUMBER(5,0),
    HIGH_QUANTITY NUMBER(5,0),
    DISCOUNT NUMBER(4,2) NOT NULL,
    CONSTRAINT FK_DISCOUNTS_STORE_ID FOREIGN KEY (STORE_ID) REFERENCES STORES (STORE_ID)
);

INSERT INTO DISCOUNTS VALUES ('Initial Customer', NULL, NULL, NULL, 10.5);
INSERT INTO DISCOUNTS VALUES ('Volume Discount', NULL, 100, 1000, 6.7);
INSERT INTO DISCOUNTS VALUES ('Customer Discount', '8042', NULL, NULL, 5.0);
