DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'PUBLISHERS';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE PUBLISHERS CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE PUBLISHERS(
    PUBLISHER_ID CHAR(4) NOT NULL,
    PUBLISHER_NAME VARCHAR2(40),
    CITY VARCHAR2(20),
    STATE CHAR(2),
    COUNTRY VARCHAR2(30) DEFAULT('USA'),
    CONSTRAINT PK_PUBLISHERS PRIMARY KEY (PUBLISHER_ID),
    CONSTRAINT CK_PUBLISHERS_PUBLISHER_ID CHECK(PUBLISHER_ID IN ('1389', '0736', '0877', '1622', '1756') OR REGEXP_LIKE(PUBLISHER_ID, '^99[0-9]{2}$'))
);

INSERT INTO PUBLISHERS VALUES ('0736', 'New Moon Books', 'Boston', 'MA', 'USA');
INSERT INTO PUBLISHERS VALUES ('0877', 'Binnet & Hardley', 'Washington', 'DC', 'USA');
INSERT INTO PUBLISHERS VALUES ('1389', 'Algodata Infosystems', 'Berkeley', 'CA', 'USA');
INSERT INTO PUBLISHERS VALUES ('9952', 'Scootney Books', 'New York', 'NY', 'USA');
INSERT INTO PUBLISHERS VALUES ('1622', 'Five Lakes Publishing', 'Chicago', 'IL', 'USA');
INSERT INTO PUBLISHERS VALUES ('1756', 'Ramona Publishers', 'Dallas', 'TX', 'USA');
INSERT INTO PUBLISHERS VALUES ('9901', 'GGG'|| CHR(38) ||'G', 'M�nchen', NULL, 'Germany');
INSERT INTO PUBLISHERS VALUES ('9999', 'Lucerne Publishing', 'Paris', NULL, 'France');