DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'CUSTOMER_DEMO_GRAPHICS';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_DEMO_GRAPHICS CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE CUSTOMER_DEMO_GRAPHICS(
    CUSTOMER_TYPE_ID CHAR(10) NOT NULL,
    CUSTOMER_DESC CLOB NULL,
    CONSTRAINT PK_CUSTOMER_DEMO_GRAPHICS PRIMARY KEY (CUSTOMER_TYPE_ID)
);