DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'EMPLOYEE_TERRITORIES';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE_TERRITORIES CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE EMPLOYEE_TERRITORIES(
    EMPLOYEE_ID NUMBER(10,0) NOT NULL,
    TERRITORY_ID VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EMPLOYEE_TERRITORIES PRIMARY KEY (EMPLOYEE_ID, TERRITORY_ID),
    CONSTRAINT FK_EMPLOYEE_TERRITORIES_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_EMPLOYEE_TERRITORIES FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORIES (TERRITORY_ID) 
);

ALTER TABLE EMPLOYEE_TERRITORIES DISABLE CONSTRAINT FK_EMPLOYEE_TERRITORIES_ID;
ALTER TABLE EMPLOYEE_TERRITORIES DISABLE CONSTRAINT FK_EMPLOYEE_TERRITORIES;

INSERT INTO EMPLOYEE_TERRITORIES VALUES (1, '06897');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (1, '19713');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '01581');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '01730');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '01833');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '02116');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '02139');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '02184');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (2, '40222');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (3, '30346');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (3, '31406');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (3, '32859');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (3, '33607');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (4, '20852');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (4, '27403');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (4, '27511');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '02903');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '07960');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '08837');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '10019');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '10038');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '11747');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (5, '14450');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (6, '85014');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (6, '85251');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (6, '98004');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (6, '98052');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (6, '98104');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '60179');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '60601');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '80202');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '80909');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '90405');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '94025');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '94105');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '95008');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '95054');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (7, '95060');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (8, '19428');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (8, '44122');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (8, '45839');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (8, '53404');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '03049');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '03801');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '48075');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '48084');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '48304');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '55113');
INSERT INTO EMPLOYEE_TERRITORIES VALUES (9, '55439');

ALTER TABLE EMPLOYEE_TERRITORIES ENABLE CONSTRAINT FK_EMPLOYEE_TERRITORIES_ID;
ALTER TABLE EMPLOYEE_TERRITORIES ENABLE CONSTRAINT FK_EMPLOYEE_TERRITORIES;