DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'REGION';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE REGION CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE REGION(
    REGION_ID NUMBER(10,0) NOT NULL,
    REGION_DESCRIPTION CHAR(50) NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (REGION_ID)
);

INSERT INTO REGION VALUES (1, 'Eastern');
INSERT INTO REGION VALUES (2, 'Western');
INSERT INTO REGION VALUES (3, 'Northern');
INSERT INTO REGION VALUES (4, 'Southern');