DECLARE
    V_EXIST NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO V_EXIST
      FROM USER_TABLES
     WHERE TABLE_NAME = 'TERRITORIES';
    IF V_EXIST <> 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE TERRITORIES CASCADE CONSTRAINT PURGE';
    END IF; 
END;
/

CREATE TABLE TERRITORIES(
    TERRITORY_ID VARCHAR2(20) NOT NULL,
    TERRITORY_DESCRIPTION CHAR(50) NOT NULL,
    REGION_ID NUMBER(10,0) NOT NULL,
    CONSTRAINT PK_TERRITORIES PRIMARY KEY (TERRITORY_ID),
    CONSTRAINT FK_TERRITORIES_REGION FOREIGN KEY (REGION_ID) REFERENCES REGION (REGION_ID)
);


ALTER TABLE TERRITORIES DISABLE CONSTRAINT FK_TERRITORIES_REGION;

INSERT INTO TERRITORIES VALUES ('01581', 'Westboro', 1);
INSERT INTO TERRITORIES VALUES ('01730', 'Bedford', 1);
INSERT INTO TERRITORIES VALUES ('01833', 'Georgetow', 1);
INSERT INTO TERRITORIES VALUES ('02116', 'Boston', 1);
INSERT INTO TERRITORIES VALUES ('02139', 'Cambridge', 1);
INSERT INTO TERRITORIES VALUES ('02184', 'Braintree', 1);
INSERT INTO TERRITORIES VALUES ('02903', 'Providence', 1);
INSERT INTO TERRITORIES VALUES ('03049', 'Hollis', 3);
INSERT INTO TERRITORIES VALUES ('03801', 'Portsmouth', 3);
INSERT INTO TERRITORIES VALUES ('06897', 'Wilton', 1);
INSERT INTO TERRITORIES VALUES ('07960', 'Morristown', 1);
INSERT INTO TERRITORIES VALUES ('08837', 'Edison', 1);
INSERT INTO TERRITORIES VALUES ('10019', 'New York', 1);
INSERT INTO TERRITORIES VALUES ('10038', 'New York', 1);
INSERT INTO TERRITORIES VALUES ('11747', 'Mellvile', 1);
INSERT INTO TERRITORIES VALUES ('14450', 'Fairport', 1);
INSERT INTO TERRITORIES VALUES ('19428', 'Philadelphia', 3);
INSERT INTO TERRITORIES VALUES ('19713', 'Neward', 1);
INSERT INTO TERRITORIES VALUES ('20852', 'Rockville', 1);
INSERT INTO TERRITORIES VALUES ('27403', 'Greensboro', 1);
INSERT INTO TERRITORIES VALUES ('27511', 'Cary', 1);
INSERT INTO TERRITORIES VALUES ('29202', 'Columbia', 4);
INSERT INTO TERRITORIES VALUES ('30346', 'Atlanta', 4);
INSERT INTO TERRITORIES VALUES ('31406', 'Savannah', 4);
INSERT INTO TERRITORIES VALUES ('32859', 'Orlando', 4);
INSERT INTO TERRITORIES VALUES ('33607', 'Tampa', 4);
INSERT INTO TERRITORIES VALUES ('40222', 'Louisville', 1);
INSERT INTO TERRITORIES VALUES ('44122', 'Beachwood', 3);
INSERT INTO TERRITORIES VALUES ('45839', 'Findlay', 3);
INSERT INTO TERRITORIES VALUES ('48075', 'Southfield', 3);
INSERT INTO TERRITORIES VALUES ('48084', 'Troy', 3);
INSERT INTO TERRITORIES VALUES ('48304', 'Bloomfield Hills', 3);
INSERT INTO TERRITORIES VALUES ('53404', 'Racine', 3);
INSERT INTO TERRITORIES VALUES ('55113', 'Roseville', 3);
INSERT INTO TERRITORIES VALUES ('55439', 'Minneapolis', 3);
INSERT INTO TERRITORIES VALUES ('60179', 'Hoffman Estates', 2);
INSERT INTO TERRITORIES VALUES ('60601', 'Chicago', 2);
INSERT INTO TERRITORIES VALUES ('72716', 'Bentonville', 4);
INSERT INTO TERRITORIES VALUES ('75234', 'Dallas', 4);
INSERT INTO TERRITORIES VALUES ('78759', 'Austin', 4);
INSERT INTO TERRITORIES VALUES ('80202', 'Denver', 2);
INSERT INTO TERRITORIES VALUES ('80909', 'Colorado Springs', 2);
INSERT INTO TERRITORIES VALUES ('85014', 'Phoenix', 2);
INSERT INTO TERRITORIES VALUES ('85251', 'Scottsdale', 2);
INSERT INTO TERRITORIES VALUES ('90405', 'Santa Monica', 2);
INSERT INTO TERRITORIES VALUES ('94025', 'Menlo Park', 2);
INSERT INTO TERRITORIES VALUES ('94105', 'San Francisco', 2);
INSERT INTO TERRITORIES VALUES ('95008', 'Campbell', 2);
INSERT INTO TERRITORIES VALUES ('95054', 'Santa Clara', 2);
INSERT INTO TERRITORIES VALUES ('95060', 'Santa Cruz', 2);
INSERT INTO TERRITORIES VALUES ('98004', 'Bellevue', 2);
INSERT INTO TERRITORIES VALUES ('98052', 'Redmond', 2);
INSERT INTO TERRITORIES VALUES ('98104', 'Seattle', 2);

ALTER TABLE TERRITORIES ENABLE CONSTRAINT FK_TERRITORIES_REGION;