CREATE OR REPLACE VIEW TITLE_VIEW
AS
    SELECT T.TITLE, 
           TA.AUTHOR_ORDER, 
           A.AUTHOR_LAST_NAME,
           T.PRICE, 
           T.YEAR_TO_DATE_SALES, 
           T.PUBLISHER_ID
      FROM AUTHORS A
      JOIN TITLE_AUTHOR TA ON A.AUTHOR_ID = TA.AUTHOR_ID
      JOIN TITLES T ON TA.TITLE_ID = T.TITLE_ID;